### ISSUE TITLE
unable to use "it " block inside shared example block

### ISSUE THREAD

**Issue by chandanaGollapudi** [railsware/rspec-example_steps#16]
Hi ,

I am not able to use "it" block inside "shared_steps" block as described in below link.
https://github.com/LRDesign/rspec-steps
code
![shared_steps_with_itblock](https://cloud.githubusercontent.com/assets/11437366/7532576/1776a57e-f586-11e4-9bc0-21ebc883aa24.jpg)

Error Message
![error_msg](https://cloud.githubusercontent.com/assets/11437366/7532580/1ed3f0e2-f586-11e4-9b52-c13eb5c5a71e.jpg)

but other example worked fine that has When, Given,And and Given blocks provided under below link .

https://github.com/railsware/rspec-example_steps

code
![shared_steps_with_gerkin](https://cloud.githubusercontent.com/assets/11437366/7532584/2addabe4-f586-11e4-8c9b-61e780a204bb.jpg)

could you please help me in understanding  below points

can i use "it " block under "shared_steps" ?

is gem 'rspec-example_steps' supports Gherkin Language by default?

for example, if i am using multiple steps under "describe " block , how to skip remaining steps , if one step fail?

Along with Step block description I would like to add (Given, When, And, Then ) blocks description to HTML report .  please let me know different gems/ways that are available to support this.

thanks,
Chandana

**Comment by ayanko** [comment]
Use [shared_exampes](https://www.relishapp.com/rspec/rspec-core/v/3-2/docs/example-groups/shared-examples) when you want to re-use **examples**.
Use shared_steps when you want to re-use **steps**.

Theoretically you can re-use shared steps inside shared examples. 
I hope next example gives your full picture:


```ruby
shared_steps :my_feature_fail_steps do
  When 'I visit bla'
  Then 'I should see'
end

shared_examples_for :my_feature_examples do
  Steps 'User tries to creates entity with invalid data' do
    When 'I go bla' ...
    include_steps :my_feature_fail_steps
    When 'I go bla 2'
  end
end

feature 'Bla' do
  context 'guest user' do
    before { logged_as guest }

    include_examples :my_feature_examples

    Steps 'User tries to bla2' do
      When 'I visit bla2'
      include_steps :my_feature_fail_steps
    end

    Steps 'User tries to bla3' do
      When 'I visit bla3'
      include_steps :my_feature_fail_steps
      Then 'bla 3'
      And 'bla 3'
    end

  end
end
```

**Comment by ayanko** [comment]
Suggestions given. Close as invalid.
